#!/bin/sh

rm -rf src/doc
cp src/0*.css ../mitmproxy/doc-src
cp -r ../mitmproxy/doc-src src/doc
rm src/doc/0*.css*
rm src/doc/mitmproxy-long.png
cp ./src/_doclayout.html ./src/doc/_layout.html

#cp  ~/mitmproxy/mitmproxy/dist/*.gz src/download
