#!/bin/sh

rm -rf src/doc
cp -r ../mitmproxy/doc-src src/doc
rm src/doc/01-vendor*
rm src/doc/mitmproxy-long.png
cp ./src/_doclayout.html ./src/doc/_layout.html

#cp  ~/mitmproxy/mitmproxy/dist/*.gz src/download
