#!/bin/sh

aws configure set preview.cloudfront true
aws --profile mitmproxy \
    s3 sync --acl public-read ./rendered s3://www.mitmproxy.org/
aws --profile mitmproxy \
    cloudfront create-invalidation --distribution-id E18EVZZRMM1SSD \
    --paths "/*"
